CREATE TABLE TALLERES(
  ID_TALLER NUMERIC (6) NOT NULL PRIMARY KEY,
  NOMBRE varchar2(120),
  DESCRIPCION VARCHAR2(280),
  ESTADO CHAR(1) DEFAULT '1'
);
CREATE SEQUENCE SEQ_TALLER;
INSERT INTO TALLER(ID_TALLER,NOMBRE,DESCRIPCION) VALUES (SEQ_TALLER.nexval,'Spring boot','Curso de spring boot.');
INSERT INTO TALLER(ID_TALLER,NOMBRE,DESCRIPCION) VALUES (SEQ_TALLER.nexval,'Java','Curso de Java.');